spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        connection:
          isolation: 2
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    jpa:
      repositories:
        bootstrap-mode: DEFAULT
logging:
  level:
    org:
      hibernate:
        type: trace